const mongoose =require('mongoose');

const userSchema=new mongoose.Schema({
    fullName:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        unique:true,
        lowercase:true,
        trim:true
    },
    phoneNumber:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true
    },
    role:{
        type:String,
        enum:['CUSTOMER',
            'RESTAURANT_OWNER',
            'DELIVERY_PARTNER',
            'ADMIN'],
        required:true
    },
    isVerified:{
        type:Boolean,
        default:false
    },
    status:{
        type:String,
        enum:['ACTIVE','INACTIVE','BANNED'],
        default:'ACTIVE'
    },
    refreshToken:{
        type:String,
        default:null
    },
    },{
        timestamps:true
    })
const User=mongoose.model("User",userSchema);
module.exports=User;
